version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "7096:3000"
    image: t3-app
    environment:
      - DATABASE_URL="postgresql://vesl-ml-game:AVNS_kbEeOo8ivWddRqDAu6Q@canvas-dev-db1-do-user-11811149-0.b.db.ondigitalocean.com:25061/vesl-ml-game-pool?sslmode=require&pgbouncer=true"
      - NEXTAUTH_URL="https://mlapp.xancorp.us"
      - NEXTAUTH_SECRET="bIMt9dgK4sgQ1FvRAcOkbu5ozJqFSWLN3BOgbBcJbIw=""
      - DISCORD_CLIENT_ID="1133155224488525917"
      - DISCORD_CLIENT_SECRET="Et_lvWsOFBuzu_pSVY_FaVYQ4q7fzxq5"
